when svntag can not get revision from tag, delete it and copy from trunk.

diff --git a/svntag b/svntag
--- a/svntag
+++ b/svntag
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Time-stamp: <03/30/2009 14:26:18 星期一 by ahei>
+# Time-stamp: <03/30/2009 15:30:31 星期一 by ahei>
 
 readonly PROGRAM_NAME="svntag"
 readonly PROGRAM_VERSION="1.0"
@@ -155,35 +155,39 @@ fi
 
 dateTimeRegexp="[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2} [[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}"
 
+executeCommand "svn up ${trunkDir}" "${isExecute}" "$isQuiet" "$isStop"
+
 # merge tag
 if [ -d "${tagsDir}/${tagName}" ]; then
+    executeCommand "svn up ${tagsDir}/${tagName}" "${isExecute}" "$isQuiet" "$isStop"
+
     fromRevisionNo=`svn log "${tagsDir}/${tagName}" -r COMMITTED | sed -n 4p | sed -r "s/^Create tag ${tagName} from trunk r([[:digit:]]+)\.$/\1/g" | grep -x -E "[[:digit:]]+"`
     if [ -z "${fromRevisionNo}" ]; then
         fromRevisionNo=`svn log "${tagsDir}/${tagName}" -r COMMITTED | sed -n 4p | sed -r "s/^Merge trunk r[[:digit:]]+:([[:digit:]]+) to tag ${tagName}\.$/\1/g" | grep -x -E "[[:digit:]]+"`
     fi
     if [ -z "${fromRevisionNo}" ]; then
-        echo "Get from revision number of ${tagsDir}/${tagName} failed."
-        exit 1
+        executeCommand "svn rm ${tagsDir}/$tagName" "${isExecute}" "$isQuiet" "$isStop"
+        executeCommand "svn ci ${tagsDir}/$tagName -m \"Delete tag $tagName by $PROGRAM_NAME, because can not get revision from it's log.\"" "${isExecute}" "$isQuiet" "$isStop"
+        createTag=1
     fi
 
-    executeCommand "svn up ${trunkDir}" "${isExecute}" "$isQuiet" "$isStop"
-    executeCommand "svn up ${tagsDir}/${tagName}" "${isExecute}" "$isQuiet" "$isStop"
-
-    if [ "${tagName}" = "release" ]; then
-        dateTime=`svn log "${tagsDir}/${tagName}" -r COMMITTED | sed -n 2p | sed -r "s/^r[[:digit:]]+ \| .+ \| (${dateTimeRegexp}).* \| .*$/\1/g" | grep -x -E "${dateTimeRegexp}" | sed "s/ /-/g"`
-        if [ -z "${dateTime}" ]; then
-            echo "Get date time of tag ${tagName} failed."
-            exit 1
-        fi
+    if [ "$createTag" != 1 ]; then
+        if [ "${tagName}" = "release" ]; then
+            dateTime=`svn log "${tagsDir}/${tagName}" -r COMMITTED | sed -n 2p | sed -r "s/^r[[:digit:]]+ \| .+ \| (${dateTimeRegexp}).* \| .*$/\1/g" | grep -x -E "${dateTimeRegexp}" | sed "s/ /-/g; s/:/_/g"`
+            if [ -z "${dateTime}" ]; then
+                echo "Get date time of tag ${tagName} failed."
+                exit 1
+            fi
             
-        executeCommand "svn cp ${tagsDir}/${tagName} ${tagsDir}/${tagName}_${dateTime}" "${isExecute}" "$isQuiet" "$isStop"
-    fi
+            executeCommand "svn cp ${tagsDir}/${tagName} ${tagsDir}/${tagName}_${dateTime}" "${isExecute}" "$isQuiet" "$isStop"
+        fi
 
-    toRevisionNo=`getRevisionNo "${trunkDir}"`
-    executeCommand "svn merge ${trunkDir} -r${fromRevisionNo}:${toRevisionNo} ${tagsDir}/${tagName}" "${isExecute}" "$isQuiet" "$isStop"
-    executeCommand "svn ci -m \"Merge trunk r${fromRevisionNo}:${toRevisionNo} to tag ${tagName}.\"" "${isExecute}" "$isQuiet" "$isStop"
-    
-    exit
+        toRevisionNo=`getRevisionNo "${trunkDir}"`
+        executeCommand "svn merge ${trunkDir} -r${fromRevisionNo}:${toRevisionNo} ${tagsDir}/${tagName}" "${isExecute}" "$isQuiet" "$isStop"
+        executeCommand "svn ci -m \"Merge trunk r${fromRevisionNo}:${toRevisionNo} to tag ${tagName}.\"" "${isExecute}" "$isQuiet" "$isStop"
+        
+        exit
+    fi
 fi
 
 # create tag
@@ -193,7 +197,5 @@ if [ -z "${revisionNo}" ]; then
     exit 1
 fi
 
-executeCommand "svn up ${trunkDir}" "${isExecute}" "$isQuiet" "$isStop"
-executeCommand "svn up ${tagsDir}/${tagName}" "${isExecute}" "$isQuiet" "$isStop"
 executeCommand "svn cp ${trunkDir} ${tagsDir}/${tagName}" "${isExecute}" "$isQuiet" "$isStop"
 executeCommand "svn ci -m \"Create tag ${tagName} from trunk r${revisionNo}.\"" "${isExecute}" "$isQuiet" "$isStop"
